FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine
LABEL author "Tomás Migone"
LABEL maintainer "tomasmigone@gmail.com"

# Enable udev for detection of dynamically plugged devices
ENV UDEV=on
COPY usb.rules /etc/udev/rules.d/usb.rules

# Install dependencies
RUN install_packages rsync findmnt

WORKDIR /app
COPY . .
RUN chmod +x /app/start.sh
RUN chmod +x /app/copy.sh

CMD [ "/app/start.sh" ]